fs-webdev/styles-wc

fs-person/fs-person.html
This will make the portrait image display on top of the placeholder icon and not next to it. Primarily, this is for fixing broken images where both are seen. Regular portraits, or those without portraits appear to be fine.
Before: 
After:
=> Change fs-person portrait image element to position: absolute

fs-icon/fs-icon.html, fs-person/fs-person.html
Set 100% width on each parent container, so that text-overflow: ellipsis can function.
Specify min-height and min-width for fs-icons, so that they do not scale smaller because of the 100% widths or when the base font size changes.
Reviewed-by: Drew McMurry
=> person-renderer: Add ellipses-truncation

fs-person/fs-person.html
hidePid is needed because inline people sometimes have a pid for opening person card, but we don't want to show it.
_openPersonCard() checks to see if the attribute is set and the person card exists on the page before triggering an event. The event listener and handler is in [person-card.html](https://github.com/fs-webdev/tree/blob/person-card/assets/elements/person-card/person-card.html#L433-L458). Although using a global event isn't the greatest way of doing things, it allows us to open a single instance of person card from anywhere without having to import it as a dependency (which would create a circular dependency if added here).
As a side note, we want to keep the destination href with openPersonCard, so that the href can be opened instead of the person card when a cmd + click or …
=> Add openPersonCard and hidePid attributes.

fs-person/fs-person.html
This makes it so clicking on the copy icon doesn't open the person card or person page.
=> Prevent other events from firing when copy icon is clicked.

fs-person/fs-person.html
Since we changed fs-tree-person-renderer to use click events, this needs to change as well so it can stop them from firing.
=> Fix the copy icon to work with other click events.

bower.json, fs-person/fs-person.html
I couldn't find any problems while testing absolute positioned portraits. If something comes up where they don't fit in their container, we'll investigate it more.
=> Bug fixes for portraits in ie11.

fs-person/fs-person.html
This makes it so the on-click doesn't fire when clicking on the pid.
Unit tests still pass.
=> Move on-click function listener from span to inner fs-icon

bower.json, fs-person/demo/index.html, fs-person/fs-person.html, test/fs-person_test.html
Add hideSeparator check (replaces _and() function)
CSS fixes: allow overflow for PID copier tooltip & cursor: pointer only on button.
Add/update unit tests.
=> fs-person: add hide-separator property

bower.json, fs-button/fs-button.html
When the spinner is only hidden in the DOM it causes performance issues. This should prevent the spinner from being in the DOM at all times and only render it when appropriate.
=> Updates when the spinner is actually in the dom

bower.json, fs-person/fs-person.html
For an unknown reason, the mixins for styles-wc/fs-person don't appear to be working in beta and prod (they seem alright locally). Everywhere that the mixins are working (fs-life-events, for example) the parentheses are present, so we're going to replace them here and see if that helps.
=> Possible bug fix for CSS mixins

bower.json, fs-person/fs-person.html
Changing from display: inline-flex to display: flex allows the wrapping container to adjust its size dynamically, instead of allowing the content to spill out.
=> Bug fix: Person names spill out of pedigree containers

bower.json, fs-person/demo/index.html, fs-person/fs-person.html, test/fs-person_test.html
The functionality to copy the PID is fixed as part of this. For some reason the width of the hidden input was causing the problem for person-card. I've tested it out and increasing the width of the hidden input seems to fix the issue.
There's also a change to make it so the PID itself will copy when clicked, so the tooltip has to show when hovering over that as well. This was a ruling made by Jeff Hawkins.
I've also added a unit test for making sure the aria-label gets added on copy and I added a little variety to the demo page since all of the person renderers had the same PID.
=> OFT-69102 Fix copy pid functionality

bower.json
Alphabetize dependencies.
Update dependencies & pin to minor revision.
Use full dependency URL (clickable).
Remove resolutions (https://github.com/bower/bower/issues/1362).
Release 2.1.16.
=> Bower update

test/fs-person_test.html
Until I can sit down and figure out a way to prevent the popup from appearing in IE, this test ought to be commented out. I will come back to it when I have time.
=> Comment out flakey unit test

bower.json, fs-person/demo/index.html, fs-person/fs-person.html, test/fs-person_test.html
Allows rendering of the gender dot icons when not displaying in 'inline'.
=> Adds `dot-icon` property for use-cases such as in the history-list

bower.json, fs-person/fs-person.html
Title says it all, really. I'm very confident in the `&nbsp;` fix, but the tooltip is tricky because of how `z-index` is affected by the stacking context. Increasing the `z-index` to 1000000+ won't fix it. Hopefully by giving the parent a higher `z-index` it will at least render above elements without one. This doesn't work in cases when a grand-parent element has `overflow:hidden;`, but this should at least reduce the number of times this becomes a problem.
Read more about the stacking context here: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context
=> Bug fixes for `&nbsp;` not disappearing and copy tooltip getting cut off.

fs-button/fs-button.html
Added styles to prevent weird squares showing up on buttons in IE.
The "initial" CSS property is not supported in IE so the CSS reset was not being applied.
Fixes OFT-69351.
=> Add styles for IE since initial is unsupported

.codeclimate.yml, .eslintrc.json
Incorporate Code Climate grep engine to check for <<<<<<<|=======|>>>>>>> in code
Rename .eslintrc to .eslintrc.json.
Disable no-param-reassign rule for Tyler Graf. :)
=> Code Climate: Add bad merge check

bower.json, fs-input-validation-eol/demo/index.html
Changed title for fs-input-validation-eol dempo page from fs-button to fs-input-validation-eol
=> Renamed title for demo page to correct element

bower.json, fs-person-eol/fs-person-eol.html, fs-person-eol/locales/fs-person-eol_de.json, fs-person-eol/locales/fs-person-eol_en.json, fs-person-eol/locales/fs-person-eol_eo.json, fs-person-eol/locales/fs-person-eol_es.json, fs-person-eol/locales/fs-person-eol_fr.json, fs-person-eol/locales/fs-person-eol_it.json, fs-person-eol/locales/fs-person-eol_ja.json, fs-person-eol/locales/fs-person-eol_ko.json, fs-person-eol/locales/fs-person-eol_pt.json, fs-person-eol/locales/fs-person-eol_ru.json, fs-person-eol/locales/fs-person-eol_zh.json
There were some styling issues with the Alternate Spouses dialog.
- When a spouse is "UNKNOWN" hide details.
- Added locales for the text: "[UNKNOWN NAME]"
=> Fixed JIRA TW 299

bower.json, fs-person-eol/demo/index.html, fs-person-eol/fs-person-eol.html, test/fs-person_test.html
Adds colorScheme property & nightfall styles.
- Bumps version
- Adds nightfall styles & colorScheme property (reflected to attribute as requested)
- Adds tests.
- Updates documentation
- Updates demo. Demo page styles were not working without the `<custom-style>` element.
=> TK-224503. Adds colorScheme property & nightfall styles.

bower.json, fs-person-eol/fs-person-eol.html
Even though the image is in a `dom-if`, the `src` property of the image is being set to the `portraitUrl`. The `portraitUrl` is undefined when we turn off portraits in the pedigree because the data doesn't return them. So the image still makes a request to `/pedigree/undefined` and then when that fails, there's an error handler on the image that sets `portraitUrl` to `false`, so it makes another request to `/pedigree/false`. The solution is to make the `src` an attribute only (`src$=""`) which doesn't get set if the `dom-if` is set to false.
- `src=""`=>`src$=""`
- Remove `<dom-if>`s because of this: https://www.polymer-project.org/2.0/docs/devguide/templates#dom-if
=> Bug Fix: TW-419 - /pedigree/false and /pedigree/undefined calls.

bower.json, fs-person-eol/fs-person-eol.html
Use underline instead of border to have correct hover underline color in daybreak/nightfall mode.
Before:
After:
=> fs-person: Style tweak

bower.json, fs-person-eol/fs-person-eol.html
Fix bad i18n check.  This check is preventing wci18n update to simplify boilerplate code.
Ensure that undefined will not cause an exception.
=> Fix bad i18n check

bower.json, fs-person-eol/fs-person-eol.html
Tested in IE11, Chrome, Safari, and FireFox. `flex-shrink: 0` fixes the portrait and the icon being side by side in IE11, and removing the relative/absolute positions fixes the portraits so they no longer drop when opening the children dropdown.
=> fix portrait so it no longer drops a few pixels when opening children dropdown

bower.json, fs-person-eol/fs-person-eol.html
Otherwise screen readers read the entire image url
=> add empty alt attribute to images

bower.json, fs-person-eol/fs-person-eol.html, package.json
Fix - TW-978: Make background color be transparent. This fixes problem in Safari where the background color was dark gray.
=> Fix - TW-978: Make background color be transparent.
