- fs-person/fs-person.html
This will make the "open person card" functionality work with the new shared component.
> Change selector from person-card to fs-person-card

- fs-person/fs-person.html
> Fix portrait overflow.

- bower.json
- fs-person/demo/index.html
- fs-person/fs-person.html
- test/fs-person_test.html
- test/index.html
- wct.conf.json
Let me know if the version attribute should be removed from bower.json.
> TK-189035. Adds flag for gender icon color.

- fs-person/fs-person.html
- test/fs-person_test.html
There are more tests that should be written for <fs-person>.
All of the other components in styles-wc lack unit tests.
> TK-197173. Adds unit tests for fs-person defaults.

- .gitignore
- bower.json
- fs-person/demo/index.html
- fs-person/fs-person.html
- test/fs-person_test.html
This is needed for Tree V8 pedigree.
> TK-199200. Adds hideGender to hide small portrait.

- bower.json
- fs-person/fs-person.html
This is needed for Tree V8 pedigree.
> TK-199200. Adds --fs-person-details for CSS overrides.

- bower.json
- fs-person/fs-person.html
*gender icons now match the size of gender icons as seen in temple-list (as per mark gowans)
> Updates additional styles for fs-person

- bower.json
- fs-person/demo/index.html
- fs-person/fs-person.html
> Fix ellipses issues when the parent of fs-person is too narrow.

- bower.json
> Updates version in bower.js (for previous commit).

- bower.json
- fs-icon/demo/index.html
- fs-icon/fs-icon.html
Added a medium-small icon size (12px)
- Added medium-small icon size
> Add icon size

- bower.json
I messed up the version bump in my last PR.
- fixed version number
> fix version number for adding icon size

- bower.json
- fs-person/fs-person.html
A few sentences describing the overall goals of the pull request's commits. Reference any issues/JIRAs/dependent PR's. Should **never** be empty. Review: [CONTRIBUTING.md](/.github/CONTRIBUTING.md)
- Summarize
- Your
- Changes
> Change copy to clipboard link location

- bower.json
> Fix fs-button styles in IE

- fs-person/fs-person.html
Steven Lambert found this issue during his testing.
> Add aria-hidden and readonly

- bower.json
Update pin for accessibility update.
> Update pin to 3.0.1

- bower.json
- fs-button/fs-button.html
Remove `.fs-button` styles from `dom-if`.
> Fix polymer 1 shady dom issue with styleguide styles.

- bower.json
- fs-tooltip-eol/demo/index.html
Remove is=fs-button-eol and rename button to  <fs-button-eol></fs-button-eol>.
> Conform button extension to polymer 2 syntax.

- fs-person-eol/demo/index.html
- fs-person-eol/fs-person-eol.html
Switch from visibility to display property.
Clean up demos somewhat.
> Bug Fix: TW-375 - Bad focus outlines

- bower.json
- fs-person-eol/fs-person-eol.html
##Description
Started grouping the daybreak & nightfall styles. There is likely more to do, but it is hard to tell what the effects will be because some of the colors probably come from mixins from parent components.
- Groups daybreak & nightfall styles.
> Invert colors cleanup

- bower.json
- fs-person-eol/fs-person-eol.html
Removes bold for the names with the nightfall theme.
After
> Invert colors unbold

- bower.json
- fs-person-eol/fs-person-eol.html
- package.json
- test/fs-person_test.html
- wct.conf.json
- Convert copy pid popup into fs-anchored-dialog
- make copy pid popup appear on top of icons
- bower version bump
> make copy pid popup appear on top of icons

- bower.json
- fs-person-eol/fs-person-eol.html
- package.json
- fix copy pid padding
- bump version
> fix copy pid padding

- bower.json
- fs-person-eol/fs-person-eol.html
- fix copy pid line-height
- bump bower
> fix copy pid line height

- .codeclimate.yml
- .travis.yml
- README.md
- bower.json
- package.json
- wct.conf.json
- wct.conf.windows.json
Travis env vars updated, and corresponding .travis.yml entries removed/updated.
Add babel-eslint parser to future-proof against esoteric ES6 functions.
Split WCT browser runs for greater stability.
Ignore all files except production code in bower:ignore to cut down on install time.
Release version 4.2.5.
> Build: Update configurations
